### ISSUE TITLE
Additional popular CI services

### ISSUE THREAD

**Issue by aleksei-bulgak** [madhead/awesome-ci#2]
Hi it would be great to add some additional CI services to this comparison.
For example:
- [GoCD](https://www.gocd.org/) - this service already has some [integration with github](https://www.gocd.org/2015/07/07/GitHub-Integration/)
- [Concourse CI](https://concourse.ci/) - also has some [third party plugins](https://github.com/jtarchie/github-pullrequest-resource)
- [CodePipeline](https://aws.amazon.com/documentation/codepipeline/)/[CodeBuild](https://aws.amazon.com/codebuild/) - do not  exactly how it works with github but think it is also popular tool.

**Comment by madhead** [comment]
GoCD and Concourse - 👍, CodeBuild - need to think about it, look like not very popular.
